# Generated by Django 5.0.4 on 2024-04-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=200)),
                ('appontmentdate', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('doctorname', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=150)),
            ],
        ),
    ]
