# Generated by Django 5.0.4 on 2024-04-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appontmentdate',
            new_name='appointmentdate',
        ),
    ]
