# Generated by Django 5.0.4 on 2024-04-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_appontmentdate_appointment_appointmentdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentnumber', models.CharField(max_length=200)),
                ('departmentname', models.CharField(max_length=200)),
                ('doctorname', models.CharField(max_length=200)),
            ],
        ),
    ]
