# Generated by Django 5.0.4 on 2024-04-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_address_contact_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='pname',
        ),
    ]
