# Generated by Django 5.0.4 on 2024-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_doctor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
